### ISSUE TITLE
New Word Count Counts Non-Words

### ISSUE THREAD

**Issue by Justintime50** [jasonappah/wordcounter#3]
It looks like the word counter logic breaks words when the string of alphabetical character is broken by *any* character. Take for instance this awful example below, it's technically 38 words (hyphens create a new word, periods create a new word, commas, pipes, etc) according to the app but really by my count is 9 (strings of characters broken up by spaces).

```
wSAFDSFG D SFAS FS DAS FAD. S. HELLo-WWASDF-A-A-A-A-A-A-A-A-A--A-A-A-A-A-A-.A.A.A.A.A.A.A. HELLO THERE,A,A,A,A,|H
```

It totally depends how you want to count words, but to me, hyphenated words could be a single word, words with periods in them are just one word (eg: Rocket.Chat). It may be interesting to explore adding an option to keep the logic as it is now and add a toggle to count new words at spaces/line breaks only.

**Comment by jasonappah** [comment]
Hmm. I agree that hyphenated words should be counted as a single word, but I'd prefer keeping words with periods between them as separate words. My main concern is forgetting to type a space between 2 sentences which would then throw off the count, but I can definitely add a switch to change that rule. Before that happens I probably need to implement an actual config menu, because it's probably not going to be sustainable to keep adding buttons to the bottom of the page.

**Comment by Justintime50** [comment]
Any news on this?

**Comment by Justintime50** [comment]
Clearly not a priority, closing.
